#!/usr/bin/env python
#
# Copyright (c) 2015 10X Genomics, Inc. All rights reserved.
#
DEFAULT_MIN_SNP_CALL_QUAL = 50
DEFAULT_MIN_BCS_PER_SNP = 2
DEFAULT_MIN_SNP_OBS = 10
DEFAULT_BASE_ERROR_RATE = 1e-3
DEFAULT_MIN_SNP_BASE_QUAL = 20
REGION_SPLIT_SIZE = 0.5 * 10 ** 6